config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'articles/index'
  root 'candidates#index'
  resources :articles
  resources :projects
  resources :experiences, except: [:show]
  resources :skills, except: [:show]
  resources :educations do
    resources :courses
  end
  resources :languages, except: [:show]
  resources :conferences, except: [:show]
  resources :testimonials, except: [:show]
  resources :contacts, only: [:new, :create]
  resources :institutions do
    resources :certificates
  end

  resources :newsletters, only: [:create]
  resources :charges

  get 'tags/:tag' => 'articles#tags', as: 'tag'

end

app/models/article.rb
class Article < ActiveRecord::Base

  is_impressionable
  acts_as_taggable_on :tags

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title,:content,:tag_list, presence:true
  validates :title, length: {minimum: 5}
  validates :title, :uniqueness => {:message => ' has already been taken. please make a new one! '}

  has_attached_file :article_image, :styles => { :large => "900x500", :medium => "300x300", :thumb => "100x100>" }
  validates_attachment_content_type :article_image, :content_type => /\Aimage\/.*\Z/

end

app/models/certificate.rb
class Certificate < ActiveRecord::Base

  belongs_to :institution
  validates :institution_title,:course_title,:score, presence:true


  has_attached_file :institution_logo, :styles => {:thumb => "100x100>" }
  validates_attachment_content_type :institution_logo, :content_type => /\Aimage\/.*\Z/
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  validates :name,:location, presence:true
  validates :link, :format => URI::regexp(%w(http https))
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
        :subject => 'Contact Form',
        :to => 'adamdebbagh@gmail.com',
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :education
  validates :course_title,:course_grade,:establishment, presence:true


  has_attached_file :establishment_logo, :styles => {:thumb => "100x100>" }
  validates_attachment_content_type :establishment_logo, :content_type => /\Aimage\/.*\Z/

end

app/models/education.rb
class Education < ActiveRecord::Base
  has_many :courses
  validates :major,:university,:year, presence:true


  has_attached_file :university_logo, :styles => {:thumb => "100x100>" }
  validates_attachment_content_type :university_logo, :content_type => /\Aimage\/.*\Z/

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  validates :title,:organization,:period, presence:true
  validates :website, :format => URI::regexp(%w(http https))

end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :certificates

  validates :title, presence:true
  validates :website, :format => URI::regexp(%w(http https))


  has_attached_file :institution_image, :styles => {:medium => "300x300", :thumb => "100x100>" }
  validates_attachment_content_type :institution_image, :content_type => /\Aimage\/.*\Z/

end

app/models/language.rb
class Language < ActiveRecord::Base
  validates :title,:level,:rate, presence:true

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  validates :email, presence:true
  validates :email, length: {minimum: 10}
  validates :email, :format => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  validates :email, :uniqueness => {:message => ' already exist! '}


end

app/models/project.rb
class Project < ActiveRecord::Base
  is_impressionable

  validates :title, presence:true

  has_attached_file :project_image, :styles => { :large => "900×374", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :project_image, :content_type => /\Aimage\/.*\Z/


end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :skill_title,:skill_level,:skill_in_percentage, presence:true

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  validates :name,:company,:quote, presence:true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, :styles => { :large => "1000x1000#", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :find_certificate
  before_action :find_institution, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @institutions = Institution.all.order('created_at desc')
    @candidate = User.first
  end
  def show
    @certificates = Certificate.where(institution_id: @institution).order("created_at DESC")

  end
  def new
    @institution = Institution.new
  end

  def create
    @institution = Institution.new institution_params
    if @institution.save
      redirect_to institutions_path, notice: 'Institution successfully saved'
    else
      render 'new', alert:'Oops, something went wrong, please Try again'
    end
  end

  def edit
  end

  def update
    if @institution.update institution_params
      redirect_to institutions_path, notice: 'Institution successfully updated'
    else
      render 'edit', alert: 'Oops, something went wrong, please Try again'
    end
  end

  def destroy
    @institution.destroy
    redirect_to institutions_path
  end

  private

  def find_certificate
    @certificates = Certificate.where(institution_id: @institution).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  def find_institution
    @institution = Institution.find(params[:id])
  end

  def institution_params
    params.require(:institution).permit(:title, :website, :description, :institution_image)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/institutions/_form.html.erb
<%= form_for @institution do |f| %>
    <% if @institution.errors.any? %>
        <div class="topbar topbar-danger" id="error-message">
          <div class="container">
            <button type="button" class="close" data-dismiss="message">&times;</button>
            <h2 class="text-center"><%= pluralize(@institution.errors.count,"error")%> prevented this institution from being Saved</h2><br>
            <ol class=" notice topbar-warning">
              <% @institution.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ol>
          </div>
        </div>
    <% end %>
    <br>
    <section id="wrapper">
      <%= f.file_field :institution_image, id:"custom-input-file" %>
    </section>
    <br>
    <div class="form-group float-label-control">
      <%= f.label :title, 'Institution Name' %><br>
      <%= f.text_field :title,class:"form-control", placeholder:'Institution Name', required:true %>
    </div>

    <div class="form-group float-label-control">
      <%= f.label :website,"Web Link" %><br>
      <%= f.text_field :website, class:"form-control", placeholder:'https://', required:true %>
    </div>

    <div class="form-group float-label-control">
      <%= f.label :description,"Description" %><br>
      <%= f.text_area :description,class:"form-control", placeholder:"Description", rows:1 %>
    </div>


    <%= f.submit 'Save', class: "button button_highlight button_block" %>
    <br><br><br>

<% end%>

app/views/institutions/edit.html.erb
<% provide(:title,'Edit Institution')%>
<!--Breadcrumb-->
<header class="header-top">
  <ul class="breadcrumb">
    <div class="row">
      <div class="col-md-9">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <%= link_to root_path, class:"btn btn-info",method: :get do %><i class="fa fa-home"></i><% end %>
          <%= link_to institutions_path,class:"btn btn-info" do %><i class="fa">institutions</i><% end %>
          <%= link_to institution_path(@institution),class:"btn btn-info" do %><i class="fa"> <%= @institution.title %></i><% end %>

        </div>
      </div>
    </div>
  </ul>
</header>
<div class="container-fluid">
  <div class="section">
    <div class="section-inner">
      <h2 id="heading">Edit Institution</h2>
      <%= render 'institutions/form' %>
    </div>
  </div>
</div>

app/views/institutions/index.html.erb
<% provide(:title,'My Certified Institutions')%>
<%= render 'shared/info_card' %>
<br><br>

<div class="container-fluid">
  <div class="education section">
    <div class="section-inner">
      <h2 class="heading"> Institutions & Certificates
        <% if user_signed_in? %>
                <span class="new">
                    <%= link_to new_institution_path,  method: :get,title:'add new institution'  do %>
                        <i class="fa fa-pencil  pull-right"></i>
                    <% end %>
                </span>
        <% end %>
      </h2>

  <section>
    <div class="container">
      <% @institutions.each do |institution|%>
      <div class="collapse-card">
        <div class="title">

          <%= image_tag institution.institution_image.url(:medium),class:"profile_image image-responsive pull-left small-avatar img-responsive" %>
          <span>
            <i class="fa fa-angle-right"></i>
          </span>
          <strong><%= institution.title %></strong>
        </div>
        <div class="body">
          <%= institution.description %>
          <span class="pull-right">
             &nbsp;&nbsp;
            <%= link_to  institution_path(institution),method: :get, class:"pull-right" do %>
               My achievements <i class="fa fa-angle-double-right"></i>
            <% end %>&nbsp;&nbsp;
                <% if user_signed_in? %>
                    <%= link_to new_institution_certificate_path(institution),title:"add new certificate" do %>
                        <i class="fa fa-pencil"></i>
                    <% end %>&nbsp;&nbsp;
                <%= link_to edit_institution_path(institution),title:"edit institution"  do %>
                        <i class="fa fa-edit"></i>
                    <% end %>&nbsp;&nbsp;
                <%= link_to institution_path(institution),title:"delete institution", method: :delete, data: {confirm: "Are you sure you want to delete this post?"} do %>
                        <i class="fa fa-trash-o"></i>
                    <% end %>&nbsp;&nbsp;
                <% end %>
              </span>
        </div>
      </div>
      <% end %>
    </div>
  </section>
      </div></div>
</div>
<br><br><br>

app/views/institutions/new.html.erb
<% provide(:title,'New Institution')%>
<!--Breadcrumb-->
<header class="header-top">
  <ul class="breadcrumb">
    <div class="row">
      <div class="col-md-9">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <%= link_to root_path, class:"btn btn-info",method: :get do %><i class="fa fa-home"></i><% end %>
          <%= link_to institutions_path,class:"btn btn-info" do %><i class="fa">institution</i><% end %>
          <%= link_to new_institution_path,class:"btn btn-info" do %><i class="fa">new institution</i><% end %>

        </div>
      </div>
    </div>
  </ul>
</header>
<div class="container-fluid">
  <div class="section">
    <div class="section-inner">
        <h2 class="heading">New Institution</h2>
        <%= render 'institutions/form' %>
    </div>
  </div>
</div>

app/views/institutions/show.html.erb
<% provide(:title,"My #{@institution.title} certificates")%>
<!--Breadcrumb-->
<header class="header-top">
  <ul class="breadcrumb">
    <div class="row">
      <div class="col-md-9">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <%= link_to root_path,class:"btn btn-info", method: :get do %><i class="fa fa-home"></i><% end %>
          <%= link_to institutions_path,class:"btn btn-info" do %><i class="fa"> institutions</i><% end %>
          <!--<%#= link_to institution_certificates_path(@institution),class:"btn btn-info" do %><i class="fa"> certificates</i><%# end %>-->
          <%= link_to institution_path(@institution),class:"btn btn-info" do %><i class="fa"> <%= @institution.title %></i><% end %>

        </div>
      </div>
      <div class="col-md-3">
        <% if user_signed_in? %>
            &nbsp;<span class="control">
                <%= link_to new_institution_certificate_path(@institution, @certificate), class:"active btn btn-info btn-lg pull-right" do %>
                    <i class="fa fa-edit"> Add New Certificate</i>
                <% end %>
          </span>
        <% end %>
      </div>
    </div>
  </ul>
</header>

<!--Institution/Certificates-->

<div class="container-fluid">
  <div class="section">
    <div class="section-inner">
      <h2 class="heading"> Achievements</h2>
      <div class="table-responsive">
        <table class="table table-hover table-expandable table-striped ">
          <thead>
          <tr>
            <th><i class="fa fa-expand"></i></th>
            <th>Title</th>
            <th>Score</th>

          </tr>
          </thead>
          <tbody>
          <% @certificates.each do |certificate|%>
              <tr>
                <td><%= image_tag certificate.institution_logo.url(:thumb), class:'profile_image small-avatar image-responsive'%>
                </td>
                <td><%= certificate.course_title %></td>
                <td><%= certificate.score %></td>


              </tr>
              <tr>
                <td colspan="5"><h4>Title: <%= certificate.course_title %></h4>
                <h6>Score: <%= certificate.score %></h6>
                  <h5 class="course_issuer">Institution: <%= certificate.course_issuer %></h5>
                  <h5>Instructor:  <%= certificate.course_instructor %> </h5>
                  <%= link_to certificate.course_link, target:'_blank' do %>
                      <h5><i class="fa fa-external-link"></i> View Certificate</h5>
                  <% end %>

                  <p class="course_description"><%= simple_format certificate.description %></p>
                  <span class="pull-right">
             &nbsp;&nbsp;

                    <% if user_signed_in? %>

                         <%= link_to edit_institution_certificate_path(certificate.institution_id, certificate.id),title:"edit certificate"  do %>
                        <i class="fa fa-edit"></i>
                    <% end %>&nbsp;&nbsp;
                        <%= link_to institution_certificate_path(certificate.institution_id, certificate.id) ,title:"delete certificate", method: :delete, data: {confirm: "Are you sure you want to delete establishment"} do %>
                        <i class="fa fa-trash-o"></i>
                    <% end %>&nbsp;&nbsp;
                <% end %>
              </span>

                </td>
              </tr>
          <% end %>
          </tbody>
        </table><br><br>
      </div>
    </div><!--//section-inner-->
  </div><!--//section-->
</div><!--//container-fluid-->
<br><br>

<script>
    (function ($) {
        $(function () {
            $('.table-expandable').each(function () {
                var table = $(this);
                table.children('thead').children('tr').append('<th></th>');
                table.children('tbody').children('tr').filter(':odd').hide();
                table.children('tbody').children('tr').filter(':even').click(function () {
                    var element = $(this);
                    element.next('tr').toggle('slow');
                    element.find(".table-expandable-arrow").toggleClass("up");
                });
                table.children('tbody').children('tr').filter(':even').each(function () {
                    var element = $(this);
                    element.append('<td><div class="table-expandable-arrow"></div></td>');
                });
            });
        });
    })(jQuery);
</script>