config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'articles/index'
  root 'candidates#index'
  resources :articles
  resources :projects
  resources :experiences, except: [:show]
  resources :skills, except: [:show]
  resources :educations do
    resources :courses
  end
  resources :languages, except: [:show]
  resources :conferences, except: [:show]
  resources :testimonials, except: [:show]
  resources :contacts, only: [:new, :create]
  resources :institutions do
    resources :certificates
  end

  resources :newsletters, only: [:create]
  resources :charges

  get 'tags/:tag' => 'articles#tags', as: 'tag'

end

app/models/article.rb
class Article < ActiveRecord::Base

  is_impressionable
  acts_as_taggable_on :tags

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title,:content,:tag_list, presence:true
  validates :title, length: {minimum: 5}
  validates :title, :uniqueness => {:message => ' has already been taken. please make a new one! '}

  has_attached_file :article_image, :styles => { :large => "900x500", :medium => "300x300", :thumb => "100x100>" }
  validates_attachment_content_type :article_image, :content_type => /\Aimage\/.*\Z/

end

app/models/certificate.rb
class Certificate < ActiveRecord::Base

  belongs_to :institution
  validates :institution_title,:course_title,:score, presence:true


  has_attached_file :institution_logo, :styles => {:thumb => "100x100>" }
  validates_attachment_content_type :institution_logo, :content_type => /\Aimage\/.*\Z/
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  validates :name,:location, presence:true
  validates :link, :format => URI::regexp(%w(http https))
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
        :subject => 'Contact Form',
        :to => 'adamdebbagh@gmail.com',
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :education
  validates :course_title,:course_grade,:establishment, presence:true


  has_attached_file :establishment_logo, :styles => {:thumb => "100x100>" }
  validates_attachment_content_type :establishment_logo, :content_type => /\Aimage\/.*\Z/

end

app/models/education.rb
class Education < ActiveRecord::Base
  has_many :courses
  validates :major,:university,:year, presence:true


  has_attached_file :university_logo, :styles => {:thumb => "100x100>" }
  validates_attachment_content_type :university_logo, :content_type => /\Aimage\/.*\Z/

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  validates :title,:organization,:period, presence:true
  validates :website, :format => URI::regexp(%w(http https))

end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :certificates

  validates :title, presence:true
  validates :website, :format => URI::regexp(%w(http https))


  has_attached_file :institution_image, :styles => {:medium => "300x300", :thumb => "100x100>" }
  validates_attachment_content_type :institution_image, :content_type => /\Aimage\/.*\Z/

end

app/models/language.rb
class Language < ActiveRecord::Base
  validates :title,:level,:rate, presence:true

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  validates :email, presence:true
  validates :email, length: {minimum: 10}
  validates :email, :format => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  validates :email, :uniqueness => {:message => ' already exist! '}


end

app/models/project.rb
class Project < ActiveRecord::Base
  is_impressionable

  validates :title, presence:true

  has_attached_file :project_image, :styles => { :large => "900×374", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :project_image, :content_type => /\Aimage\/.*\Z/


end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :skill_title,:skill_level,:skill_in_percentage, presence:true

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  validates :name,:company,:quote, presence:true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, :styles => { :large => "1000x1000#", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :tags]
  impressionist :actions=>[:show]

  def index
    @articles = Article.all.order('created_at desc').paginate(page: params[:page], per_page: 3)
    @candidate = User.first
    @recent_articles = Article.all.order('created_at ASC').limit(5) # Archived Articles
    @news_signup = Newsletter.new
  end

  def show
    impressionist(@article, unique: [:impressionable_type, :impressionable_id])
    @latest_articles = Article.all.order('created_at DESC').limit(3)
    @related_articles = Article.all.tagged_with(@article.tag_list, any: true).order('created_at DESC').limit(3)
    @info_image = Article.last
    @candidate = User.first
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new article_params
    if @article.save
      redirect_to @article, notice: 'Article successfully saved'
    else
      render 'new', alert:'Oops, something went wrong, please Try again'
    end
  end

  def edit
  end

  def update
    if @article.update article_params
      redirect_to @article, notice: 'Article successfully updated'
    else
      render 'edit', alert:'Oops, something went wrong, please Try again'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  def tags
    @candidate = User.first
    if params[:tag].present?
      @articles = Article.tagged_with(params[:tag]).order('created_at desc').paginate(page: params[:page], per_page: 3)
    else
      @articles = Article.all.order('created_at desc').paginate(page: params[:page], per_page: 3)
    end
    @related_articles = Article.tagged_with(params[:tag]).order('created_at asc').limit(3)
    @recent_articles = Article.all.order('created_at DESC').limit(5) # Latest Articles

  end

  private

  def find_article
    @article = Article.friendly.find(params[:id])
  end
  def article_params
    params.require(:article).permit(:title, :caption, :summary, :content,:markdown, :tag, :category, :article_image, :slug, :tag_list)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/articles/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'discussarticle';
    var disqus_identifier = '<%= @article.id%>';
    var disqus_title = '<%= @article.title%>';
    var disqus_url = '<%= url_for([@article, {only_path: false}]) %>';


    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
    <% if @article.errors.any? %>

        <div class="topbar topbar-danger" id="error-message">
          <div class="container">
            <button type="button" class="close" data-dismiss="message">&times;</button>
            <h2 class="text-center"><%= pluralize(@article.errors.count,"error")%> prevented this article from being Saved</h2><br>
            <ol class=" notice topbar-warning">
              <% @article.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ol>
          </div>
        </div>
    <% end %>
    <br>
    <section id="wrapper">
      <%= f.file_field :article_image, id:"custom-input-file" %>
    </section>
    <br>
    <div class="form-group float-label-control">
      <%= f.label :title %><br>
      <%= f.text_field :title,class:"form-control", placeholder:"Title", required:true %>
    </div>

    <div class="form-group float-label-control">
      <%= f.label :caption,"Caption" %><br>
      <%= f.text_field :caption,class:"form-control", placeholder:"sub Title" %>
    </div>

    <div class="form-group float-label-control">
      <%= f.label :summary %><br>
      <%= f.text_area :summary,class:"form-control", placeholder:"Excerpt", rows:1 %>
    </div><br><br>

    <div class="form-group">
      <div class="container">
      <%= f.text_area :content,class:"form-control wysihtml5", placeholder:"Add your content here..", rows:10, required:true %>
    </div>
    </div>
    <br><br>
    <div class="form-group">
      <%= f.label :markdown,"Markdown Content" %><br>
      <%= f.text_area :markdown,class:"form-control", rows:5 %>
    </div>
    <div class="form-group float-label-control">
      <%= f.label :tag_list, "Tags ( separated with commas(,)" %><br>
      <%= f.text_field :tag_list,class:"form-control", placeholder: "Tags: separated with commas(,)", required:true %>
    </div>

    <%= f.submit 'Save', class: "button button_highlight button_block" %>
    <br><br><br>

<% end%>
<!--Turbolink uninitialization-->
<script>
    $(document).on('page:load', function(){
        window['rangy'].initialized = false
    })
</script>
<!--Wysiwyg-->
<script type="text/javascript">
    $(document).ready(function(){

        $('.wysihtml5').each(function(i, elem) {
            $(elem).wysihtml5({toolbar: {
                'font-styles': true,
                'color': true,
                'emphasis': {
                    'small': false
                },
                'blockquote': false,
                'lists':false,
                'html': true,
                'link': true,
                'image': true,
                'smallmodals': false
            }});
        });

    })
</script>

app/views/articles/edit.html.erb
<% provide(:title, 'Edit Article') %>
<!--Breadcrumb-->
<header class="header-top">
  <ul class="breadcrumb">
    <div class="row">
      <div class="col-md-9">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <%= link_to root_path, class:"btn btn-info",method: :get do %><i class="fa fa-home"></i><% end %>
          <%= link_to articles_path,class:"btn btn-info" do %><i class="fa">articles</i><% end %>
          <%= link_to edit_article_path(@article),class:"btn btn-info" do %><i class="fa"><%= @article.title%></i><% end %>

        </div>
      </div>
    </div>
  </ul>
</header>

<div class="container-fluid">
  <div class="section">
    <div class="section-inner">
      <h2 class="heading">Edit Article</h2>
      <%= render 'articles/form' %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<% provide(:title, 'My Articles') %>
<!--Breadcrumb-->
<header class="header-top">
  <ul class="breadcrumb">
    <div class="row">
      <div class="col-md-9">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <%= link_to root_path, class:"btn btn-info",method: :get do %><i class="fa fa-home"></i><% end %>
          <!--<div class="btn btn-default">...</div>-->
          <%= link_to articles_path,class:"btn btn-info" do %><i class="fa fa-angle-double-right">articles</i><% end %>
        </div>
      </div>
      <div class="col-md-3">
        <% if user_signed_in? %>
            &nbsp;<span class="control">
                <%= link_to new_article_path, class:"active btn btn-info btn-lg pull-right" do %>
                    <i class="fa fa-edit"> Add New Article</i>
                <% end %>
          </span>
        <% end %>
      </div>
    </div>
  </ul>
</header>


<div class="container sections-wrapper">
  <div class="row">
    <div class="primary col-md-8 col-sm-12 col-xs-12">
      <!--Articles-->
            <%= render 'articles/sections/article'%>
      </div>
    </div><!--//End primary-->

  <!--Sidebar-->
    <div class="secondary col-md-4 col-sm-12 col-xs-12">
      <!--Latest Articles-->
      <aside class="testimonials aside section">
        <div class="section-inner">
          <h2 class="heading">Archive</h2><hr>
          <div class="content">
            <div class="item">
                <%= render 'articles/sections/recent_articles'%>
            </div><!--//item-->
          </div><!--//content-->
        </div><!--//section-inner-->
      </aside><!--//section-->

      <!--TAGS CLOUD-->
      <%= render 'articles/sections/cloud_tags'%>
      <!--NewsLetter-->
      <%= render 'articles/sections/newsletter'%>
    </div><!--// End secondary-->
  </div><!--//row-->
</div><!--//masonry-->

app/views/articles/new.html.erb
<% provide(:title, 'New Article') %>
<!--Breadcrumb-->
<header class="header-top">
  <ul class="breadcrumb">
    <div class="row">
      <div class="col-md-9">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <%= link_to root_path, class:"btn btn-info",method: :get do %><i class="fa fa-home"></i><% end %>
          <%= link_to articles_path,class:"btn btn-info" do %><i class="fa">articles</i><% end %>
          <%= link_to new_article_path,class:"btn btn-info" do %><i class="fa">new article</i><% end %>

        </div>
      </div>
    </div>
  </ul>
</header>

<div class="container-fluid">
  <div class="section">
    <div class="section-inner">
      <h2 class="heading">New Article</h2>
      <%= render 'articles/form' %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<% provide(:title, "#{@article.title}") %>

<!--Breadcrumb-->
<header class="header-top">
  <ul class="breadcrumb">
    <div class="row">
      <div class="col-md-12">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <%= link_to root_path, class:"btn btn-info",method: :get do %><i class="fa fa-home"></i><% end %>
          <%= link_to articles_path,class:"btn btn-info" do %><i class="fa">articles</i><% end %>
          <%= link_to article_path(@article), class:"btn btn-info" do %><i class="fa"></i><%= @article.title.downcase.truncate(15) %><% end %>
        </div>
      </div>

    </div>
  </ul>
</header>


<div class="container sections-wrapper">
  <div class="row">
    <div class="primary col-md-8">

      <!--Article-->
          <section class="">
            <article class="section-inner article-wrap">
              <% if @article.article_image? %>
                  <%= image_tag @article.article_image.url(:large), class:"img-responsive image-effect" %>
              <% end %>
              <div class="summary">
                <h2 class="text-left"><%= @article.title.titleize %></h2>
                <h5 class=' text-muted '>
                  <%= image_tag asset_path 'favicon-16x16.png' %>
                  <%= 'adam debbagh'.titleize %>
                  <i class="glyphicon glyphicon-eye-open"></i>
                  <%= @article.impressionist_count(filter: :ip_address) %></h5>
                <br>
                <small class='text-muted'><%= @article.created_at.strftime( ' %A, ' ' %b' ' %d' ' %Y') %></small>

                <% if user_signed_in? %>
                    <div class="admin_links">
                      <%= link_to 'edit', edit_article_path(@article), method: :get %>
                      <%= link_to 'delete', article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete this post?"} %>
                    </div>
                <% end %>
                <br>
                <p><%= @article.content.html_safe %></p>
                <% unless @article.markdown.blank? %>
                    <p><%=  markdown @article.markdown %></p>
                <% end %>
                <br>

                <% @article.tags.any? %>
                <ul class="tags">
                    <% @article.tags.each do |tag| %>
                      <li><%= link_to  tag_path(tag.name), class:"tag" do %>#<%= tag.name %><% end %></li>
                    <% end %>
                </ul>
                <hr>

                <div id="share_box">
                  <p>Share this Article </p>
                  <!-- Twitter -->
                  <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @article.title %> by @AdamDebbagh - &amp;url=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
                  <!-- Facebook -->
                  <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>

                  <!-- Google Plus -->
                  <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
                </div>
                <hr>
                <!--Related Articles-->
                <div>
                    <%= render 'articles/sections/related_recent_articles_panel'%>
                </div>
                <hr>
                <br>
                <!--Disqus-->
                <%= render 'articles/disqus'%><br>
              </div><!--//content-->
            </article><!--//section-inner-->
          </section><!--//section-->
    </div><!--//End primary-->
    <!--Info Card -->
    <div class="secondary col-md-4 col-sm-12 col-xs-12">
        <%= render 'articles/sections/info_card'%>
    </div><!--// End secondary-->

  </div><!--//row-->
</div><!--//wrapper-->

<script>
    $('.tabAnchor').on('click', function() { // changes container bg to tab color stored in data attr
        var destBg = $(this).data('color');
        $('.tab-content').css('background', destBg);
    });

    $('.shifter').on('click', function(e) { // shifts tabs
        e.preventDefault();
        $('.tabToggle').toggleClass('hidden');
    });
</script>

app/views/articles/tags.html.erb
<% provide(:title, " #Tags") %>
<!--Breadcrumb-->
<header class="header-top">
  <ul class="breadcrumb">
    <div class="row">
      <div class="col-md-12">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <%= link_to root_path, class:"btn btn-info",method: :get do %><i class="fa fa-home"></i><% end %>
          <%= link_to articles_path,class:"btn btn-info" do %><i class="fa">articles</i><% end %>
          <%= link_to tag_path,class:"btn btn-info"  do %><i class="fa"> </i>Tags<% end %>
        </div>
      </div>

    </div>
  </ul>
</header>

<div class="container sections-wrapper">
  <div class="row">
    <div class="primary col-md-8 col-sm-12 col-xs-12">
      <!--Articles-->
      <% @articles.each do |article| %>
          <section class="">
            <article class="section-inner article-wrap">
              <% if article.article_image? %>
                  <%= link_to article_path(article) do %>
                      <figure>
                        <%= image_tag article.article_image.url(:large), class:"img-responsive image-effect" %>
                  <% end %>
                  <% if article.caption? %>
                      <figcaption class='caption image-effect'>
                        <span class=''><%= article.caption.titleize %></span>
                      </figcaption>
                  <% end %>
                  </figure>
              <% end %>
              <div class="summary">
                <h3 class="text-left"><%=link_to article.title.titleize, article_path(article) %></h3>
                <div class='text-muted'>
                  <div class="row clearfix">
                    <div class=" col-md-4 img-responsive" style="width: 10%">
                      <%= image_tag @candidate.image.url(:thumb), class:" small-avatar " %>
                    </div>
                    <div class=" col-md-8">
                      <h5 class="pull-left"><%= "adam debbagh".titleize %></h5>
                    </div>
                  </div>
                </div>
                <small class='text-muted'><%= article.created_at.strftime( ' %A, ' ' %b' ' %d' ' %Y') %></small>
                <br><br>
                <p><%= simple_format article.summary %></p>
                <div class="more_link">
                  <%= link_to 'Read more', article_path(article), class:" pull-right" %>
                </div>
                <br>
                <br>
              </div><!--//content-->
            </article><!--//section-inner-->
          </section><!--//section-->
      <% end %>
      <div class="pull-right">
        <%= will_paginate @articles %>
      </div>
    </div><!--//End primary-->
    <!--Sidebar-->
    <div class="secondary col-md-4 col-sm-12 col-xs-12">
      <!--Latest Articles-->
      <aside class="testimonials aside section">
        <div class="section-inner">
          <h2 class="heading"> Recent Articles</h2><hr>
          <div class="content">
            <div class="item">
              <%= render 'articles/sections/recent_articles'%>
            </div><!--//item-->
          </div><!--//content-->
        </div><!--//section-inner-->
      </aside><!--//section-->

      <!--TAGS CLOUD-->
      <%= render 'articles/sections/cloud_tags'%>
    </div><!--// End secondary-->
  </div><!--//row-->
</div><!--//masonry-->