config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'articles/index'
  root 'candidates#index'
  resources :articles
  resources :projects
  resources :experiences, except: [:show]
  resources :skills, except: [:show]
  resources :educations do
    resources :courses
  end
  resources :languages, except: [:show]
  resources :conferences, except: [:show]
  resources :testimonials, except: [:show]
  resources :contacts, only: [:new, :create]
  resources :institutions do
    resources :certificates
  end

  resources :newsletters, only: [:create]
  resources :charges

  get 'tags/:tag' => 'articles#tags', as: 'tag'

end

app/models/article.rb
class Article < ActiveRecord::Base

  is_impressionable
  acts_as_taggable_on :tags

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title,:content,:tag_list, presence:true
  validates :title, length: {minimum: 5}
  validates :title, :uniqueness => {:message => ' has already been taken. please make a new one! '}

  has_attached_file :article_image, :styles => { :large => "900x500", :medium => "300x300", :thumb => "100x100>" }
  validates_attachment_content_type :article_image, :content_type => /\Aimage\/.*\Z/

end

app/models/certificate.rb
class Certificate < ActiveRecord::Base

  belongs_to :institution
  validates :institution_title,:course_title,:score, presence:true


  has_attached_file :institution_logo, :styles => {:thumb => "100x100>" }
  validates_attachment_content_type :institution_logo, :content_type => /\Aimage\/.*\Z/
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  validates :name,:location, presence:true
  validates :link, :format => URI::regexp(%w(http https))
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
        :subject => 'Contact Form',
        :to => 'adamdebbagh@gmail.com',
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :education
  validates :course_title,:course_grade,:establishment, presence:true


  has_attached_file :establishment_logo, :styles => {:thumb => "100x100>" }
  validates_attachment_content_type :establishment_logo, :content_type => /\Aimage\/.*\Z/

end

app/models/education.rb
class Education < ActiveRecord::Base
  has_many :courses
  validates :major,:university,:year, presence:true


  has_attached_file :university_logo, :styles => {:thumb => "100x100>" }
  validates_attachment_content_type :university_logo, :content_type => /\Aimage\/.*\Z/

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  validates :title,:organization,:period, presence:true
  validates :website, :format => URI::regexp(%w(http https))

end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :certificates

  validates :title, presence:true
  validates :website, :format => URI::regexp(%w(http https))


  has_attached_file :institution_image, :styles => {:medium => "300x300", :thumb => "100x100>" }
  validates_attachment_content_type :institution_image, :content_type => /\Aimage\/.*\Z/

end

app/models/language.rb
class Language < ActiveRecord::Base
  validates :title,:level,:rate, presence:true

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  validates :email, presence:true
  validates :email, length: {minimum: 10}
  validates :email, :format => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  validates :email, :uniqueness => {:message => ' already exist! '}


end

app/models/project.rb
class Project < ActiveRecord::Base
  is_impressionable

  validates :title, presence:true

  has_attached_file :project_image, :styles => { :large => "900×374", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :project_image, :content_type => /\Aimage\/.*\Z/


end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :skill_title,:skill_level,:skill_in_percentage, presence:true

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  validates :name,:company,:quote, presence:true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, :styles => { :large => "1000x1000#", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  impressionist actions: [:show]


  def index
    @projects = Project.all.order('created_at desc')
    @candidate = User.first
    @skills = Skill.all.limit(4)
    @testimonials = Testimonial.all.limit(2)
    @educations = Education.all.limit(3)
    @conferences = Conference.all.limit(4)
    @languages = Language.all.limit(3)
  end

  def show
    @candidate = User.first
    @skills = Skill.all.limit(4)
    @testimonials = Testimonial.all.limit(2)
    @educations = Education.all.limit(3)
    @conferences = Conference.all.limit(4)
    @languages = Language.all.limit(3)
    impressionist(@project)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params
    if @project.save
      redirect_to @project, notice: 'New Project Successfully Added'
    else
      render 'new', alert: 'Oops, something went wrong, Try again'
    end
  end

  def edit
  end

  def update
    if @project.update project_params
      redirect_to @project, notice: 'Project Successfully Updated'
    else render 'edit', alert: 'Something went wrong, Try again'
    end
  end
  def destroy
    @project.destroy
    redirect_to @project
  end

  private
  def find_project
    @project = Project.find(params[:id])
  end
  def project_params
    params.require(:project).permit(:title, :subtitle,:description, :link, :project_image, :github_link, :featured)
  end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
    <% if @project.errors.any? %>
        <div class="topbar topbar-danger" id="error-message">
          <div class="container">
            <button type="button" class="close" data-dismiss="message">&times;</button>
            <h2 class="text-center"><%= pluralize(@project.errors.count,"error")%> prevented this project from being Saved</h2><br>
            <ol class=" notice topbar-warning">
              <% @project.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ol>
          </div>
        </div>
    <% end %>
    <br>

    <section id="wrapper">
      <%= f.file_field :project_image, id:"custom-input-file" %>
    </section>
    <br>
    <div class="form-group">
      <div class="checkbox-inline">
        <label class="btn btn-info">
          <%= f.check_box :featured %> Featured Project
        </label>
      </div>
    </div>
    <br>

    <div class="form-group float-label-control">
      <%= f.label :title %><br>
      <%= f.text_field :title,class:"form-control", placeholder:"Title", required:true %>
    </div>


    <div class="form-group float-label-control">
      <%= f.label :subtitle %><br>
      <%= f.text_field :subtitle,class:"form-control", placeholder:"Sub Title" %>
    </div>

    <div class="form-group float-label-control">
      <%= f.label :link, "Project Link" %><br>
      <%= f.text_field :link,class:"form-control", placeholder: "Project Link" %>
    </div>

    <div class="form-group float-label-control">
      <%= f.label :github_link, "Project Link" %><br>
      <%= f.text_field :github_link,class:"form-control", placeholder: "Source Code Link" %>
    </div>

    <div class="form-group float-label-control">
      <%= f.label :description %><br>
      <%= f.text_area :description,class:"form-control", placeholder:"Description", rows:1 %>
    </div>

    <%= f.submit 'Save', class: "button button_highlight button_block" %>
    <br><br><br>

<% end%>

app/views/projects/edit.html.erb
<% provide(:title,'Edit Project')%>
<!--Breadcrumb-->
<header class="header-top">
  <ul class="breadcrumb">
    <div class="row">
      <div class="col-md-9">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <%= link_to root_path, class:"btn btn-info",method:  :get do %><i class="fa fa-home"></i><% end %>
          <%= link_to projects_path,class:"btn btn-info" do %><i class="fa">projects</i><% end %>
          <%= link_to edit_project_path(@project),class:"btn btn-info" do %><i class="fa"><%= @project.title %></i><% end %>

        </div>
      </div>
    </div>
  </ul>
</header>

<div class="container-fluid">
  <div class="section">
    <div class="section-inner">
      <h2 class="heading">Edit Project</h2>
      <%= render 'projects/form' %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<% provide(:title,'My Projects')%>
<!--Breadcrumb-->
<header class="header-top">
  <ul class="breadcrumb">
    <div class="row">
      <div class="col-md-9">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <%= link_to root_path,class:"btn btn-info", method:  :get do %><i class="fa fa-home"></i><% end %>
          <%= link_to projects_path,class:"btn btn-info" do %><i class="fa"> projects</i><% end %>
        </div>
      </div>
      <div class="col-md-3">
        <% if user_signed_in? %>
            &nbsp;<span class="control">
                <%= link_to new_project_path, class:"active btn btn-info btn-lg pull-right" do %>
                    <i class="fa fa-edit"> Add New Project</i>
                <% end %>
          </span>
        <% end %>
      </div>
    </div>
  </ul>
</header>

<div class="container sections-wrapper">
  <div class="row">
    <div class="primary col-md-8 col-md-offset-2">
      <% @projects.each do |project|%>
      <!--Project Item-->
      <section class="latest section">
        <div class="section-inner">
          <h2 class="heading"><%= link_to project do %>
                <%= project.title %>
            <% end %></h2>
            <!--Project Item-->
                <div class="item row">
                  <%= link_to project, class:"col-md-4 col-sm-4 col-xs-12" do %>
                      <%= image_tag project.project_image.url(:medium) , class:"img-responsive image-effect" %>
                  <% end %>
                  <div class="desc col-md-8 col-sm-8 col-xs-12">
                    <h3 class="title">
                      <span class="pull-right">
                        <% if user_signed_in? %>
                            <%= link_to edit_project_path(project) do %>
                                <i class="fa fa-edit"></i>
                            <% end %>&nbsp;
                            <%= link_to project_path(project), method: :delete, data: {confirm: "Are you sure you want to delete this post?"} do %>
                                <i class="fa fa-trash-o"></i>
                          <% end %>
                        <% end %>
                    </span>
                    </h3>
                    <p> <%= project.description %>
                      <%= link_to '...read more', project_path(project)%>
                    </p>
                  </div><!--//desc-->
                </div><!--//item-->
        </div><!--//section-inner-->
      </section><!--//section-->
      <% end %>
    </div><!--//primary-->
  </div><!--//row-->
</div><!--//masonry-->

app/views/projects/new.html.erb
<% provide(:title,'New Project')%>
<!--Breadcrumb-->
<header class="header-top">
  <ul class="breadcrumb">
    <div class="row">
      <div class="col-md-9">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <%= link_to root_path, class:"btn btn-info", method: :get do %><i class="fa fa-home"></i><% end %>
          <%= link_to projects_path,class:"btn btn-info" do %><i class="fa">projects</i><% end %>
          <%= link_to new_project_path,class:"btn btn-info" do %><i class="fa">new project</i><% end %>

        </div>
      </div>
    </div>
  </ul>
</header>

<div class="container-fluid">
  <div class="section">
    <div class="section-inner">
      <h2 class="heading">New Project</h2>
      <%= render 'projects/form' %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<% provide(:title,"#{@project.title}")%>
<!--Breadcrumb-->
<header class="header-top">
  <ul class="breadcrumb">
    <div class="row">
      <div class="col-md-9">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <%= link_to root_path,class:"btn btn-info", method: :get do %><i class="fa fa-home"></i><% end %>
          <%= link_to projects_path,class:"btn btn-info" do %><i class="fa"> projects</i><% end %>
          <%= link_to project_path(@project),class:"btn btn-info" do %><i class="fa"> <%=@project.title %></i><% end %>
            </div>
      </div>
      <div class="col-md-3">
        <% if user_signed_in? %>
            &nbsp;<span class="control">
                <%= link_to new_project_path, class:"active btn btn-info btn-lg pull-right" do %>
                    <i class="fa fa-edit"> Add New Project</i>
                <% end %>
          </span>
        <% end %>
      </div>
    </div>
  </ul>
</header>

<div class="container sections-wrapper">
  <div class="row">
    <div class="primary col-md-8 col-md-offset-2">
      <!--Projects-->
      <section class="latest section">
        <div class="section-inner">
          <h2 class="heading">
            <span class="pull-left">
              <%= link_to  @project.link ,target:"_blank",title:'view website'  do %><i class="fa fa-external-link"></i><%end %>
              </span>
            <%= @project.title %> Project
            <span class="pull-right" title='views count'><i class="glyphicon glyphicon-eye-open"></i>
                <%= @project.impressionist_count(filter: :ip_address) %>
            </span>
          </h2>
          <div class="content">

            <div class="item featured text-center">
              <p class="summary"><%= @project.subtitle %></p>
              <div class="featured-image">
                <%= link_to @project.link,target:'_blank' do %>
                    <%= image_tag @project.project_image.url(:large) , class:"img-responsive project-image" %>
                <% end %>
              </div>
              <div class="desc text-left">
                <p><%= simple_format @project.description %></p>
              </div><!--//desc-->
               </div><!--//item-->
          </div><!--//content-->
        </div><!--//section-inner-->
      </section><!--//section-->
    </div><!--//secondary-->
  </div><!--//row-->
</div><!--//masonry-->