config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'articles/index'
  root 'candidates#index'
  resources :articles
  resources :projects
  resources :experiences, except: [:show]
  resources :skills, except: [:show]
  resources :educations do
    resources :courses
  end
  resources :languages, except: [:show]
  resources :conferences, except: [:show]
  resources :testimonials, except: [:show]
  resources :contacts, only: [:new, :create]
  resources :institutions do
    resources :certificates
  end

  resources :newsletters, only: [:create]
  resources :charges

  get 'tags/:tag' => 'articles#tags', as: 'tag'

end

app/models/article.rb
class Article < ActiveRecord::Base

  is_impressionable
  acts_as_taggable_on :tags

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title,:content,:tag_list, presence:true
  validates :title, length: {minimum: 5}
  validates :title, :uniqueness => {:message => ' has already been taken. please make a new one! '}

  has_attached_file :article_image, :styles => { :large => "900x500", :medium => "300x300", :thumb => "100x100>" }
  validates_attachment_content_type :article_image, :content_type => /\Aimage\/.*\Z/

end

app/models/certificate.rb
class Certificate < ActiveRecord::Base

  belongs_to :institution
  validates :institution_title,:course_title,:score, presence:true


  has_attached_file :institution_logo, :styles => {:thumb => "100x100>" }
  validates_attachment_content_type :institution_logo, :content_type => /\Aimage\/.*\Z/
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  validates :name,:location, presence:true
  validates :link, :format => URI::regexp(%w(http https))
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
        :subject => 'Contact Form',
        :to => 'adamdebbagh@gmail.com',
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :education
  validates :course_title,:course_grade,:establishment, presence:true


  has_attached_file :establishment_logo, :styles => {:thumb => "100x100>" }
  validates_attachment_content_type :establishment_logo, :content_type => /\Aimage\/.*\Z/

end

app/models/education.rb
class Education < ActiveRecord::Base
  has_many :courses
  validates :major,:university,:year, presence:true


  has_attached_file :university_logo, :styles => {:thumb => "100x100>" }
  validates_attachment_content_type :university_logo, :content_type => /\Aimage\/.*\Z/

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  validates :title,:organization,:period, presence:true
  validates :website, :format => URI::regexp(%w(http https))

end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :certificates

  validates :title, presence:true
  validates :website, :format => URI::regexp(%w(http https))


  has_attached_file :institution_image, :styles => {:medium => "300x300", :thumb => "100x100>" }
  validates_attachment_content_type :institution_image, :content_type => /\Aimage\/.*\Z/

end

app/models/language.rb
class Language < ActiveRecord::Base
  validates :title,:level,:rate, presence:true

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  validates :email, presence:true
  validates :email, length: {minimum: 10}
  validates :email, :format => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  validates :email, :uniqueness => {:message => ' already exist! '}


end

app/models/project.rb
class Project < ActiveRecord::Base
  is_impressionable

  validates :title, presence:true

  has_attached_file :project_image, :styles => { :large => "900×374", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :project_image, :content_type => /\Aimage\/.*\Z/


end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :skill_title,:skill_level,:skill_in_percentage, presence:true

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  validates :name,:company,:quote, presence:true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, :styles => { :large => "1000x1000#", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :find_education, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @educations = Education.all
    @candidate = User.first
  end

  def new
    @education = Education.new
  end
  def create
    @education = Education.new education_params
    if @education.save
      redirect_to educations_path, notice:'Successfully Saved!'
    else
      render 'new', alert:'Failed to save, please Try again'
    end
  end

  def show
    @education = Education.find(params[:id])

    @courses = Course.where(education_id: @education)
  end

  def edit
    #@course = Course.find(params[:id])
  end
  def update
    if @education.update_attributes(education_params)
      redirect_to educations_path, notice: 'Successfully Updated'
    else
      render 'edit', alert: 'Update failed, please try again'
    end
  end

  def destroy
    @education.destroy
    redirect_to @education
  end


  private
  def find_education
    @education = Education.find(params[:id])
  end
  def education_params
    params.require(:education).permit(:major, :university, :year,:university_logo)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/educations/_form.html.erb
        <%= form_for @education do |f| %>
    <% if @education.errors.any? %>
                <div class="topbar topbar-danger" id="error-message">
                  <div class="container">
                    <button type="button" class="close" data-dismiss="message">&times;</button>
                    <h2 class="text-center"><%= pluralize(@education.errors.count, "error") %> prevented this
                      institution from being Saved</h2><br>
                    <ol class=" notice topbar-warning">
                      <% @education.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                      <% end %>
                    </ol>
                  </div>
                </div>
            <% end %>
            <br>

    <section id="wrapper">
        <%= f.file_field :university_logo, id:"custom-input-file" %>
    </section>
    <br>
    <div class="form-group float-label-control">
        <%= f.label :major %><br>
        <%= f.text_field :major,class:"form-control", placeholder:"Major", required:true %>
    </div>

    <div class="form-group float-label-control">
        <%= f.label :university,"School name" %><br>
        <%= f.text_field :university,class:"form-control", placeholder:"School name", required:true %>
      </div>
    <div class="form-group float-label-control">
        <%= f.label :year,"Years of Attendance" %><br>
        <%= f.text_field :year,class:"form-control", placeholder:"Years of Attendance", required:true %>
    </div>
    <%= f.submit 'Save', class: "button button_highlight button_block" %>
    <br><br><br>

<% end%>

app/views/educations/edit.html.erb
<% provide(:title, 'Edit School')%>
<!--Breadcrumb-->
<header class="header-top">
  <ul class="breadcrumb">
    <div class="row">
      <div class="col-md-9">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <%= link_to root_path, class:"btn btn-info", method: :get do %><i class="fa fa-home"></i><% end %>
          <%= link_to education_path,class:"btn btn-info" do %><i class="fa">education</i><% end %>
          <%= link_to edit_education_path,class:"btn btn-info" do %><i class="fa">edit education</i><% end %>

        </div>
      </div>
    </div>
  </ul>
</header>
<div class="container-fluid">
  <div class="education section">
    <div class="section-inner">
        <h2 class="heading">Edit School</h2>
        <%= render 'educations/form' %>
    </div>
  </div>
</div>

app/views/educations/index.html.erb
<% provide(:title, 'My education')%>
<%= render 'shared/info_card' %>
<br><br>

<div class="container-fluid">
  <div class="education section">
    <div class="section-inner">
      <h2 class="heading">Education
        <% if user_signed_in? %>
                <span class="new">
                    <%= link_to new_education_path,method: :get  do %>
                        <i class="fa fa-pencil  pull-right"></i>
                    <% end %>
                </span>
        <% end %>
      </h2>
      <section>
        <div class="container">
          <% @educations.each do |education| %>
              <div class="collapse-card">
                <div class="title">
                  <%= image_tag education.university_logo.url(:thumb),class:"profile_image image-responsive pull-left small-avatar img-responsive" %>

            <span>
                <i class="fa fa-angle-right"></i>
            </span>
                  <strong><%= education.major %></strong>
                </div>
                <div class="body">
                  <%= education.university %><br><span class="year"><%= education.year %></span>
            <span class="pull-right">
             &nbsp;&nbsp;
              <%= link_to  education_path(education), method: :get ,class:"pull-right" do %>
               My achievements <i class="fa fa-angle-double-right"></i>
            <% end %>&nbsp;&nbsp;
              <% if user_signed_in? %>
                    <%= link_to new_education_course_path(education),title:"add new course" do %>
                        <i class="fa fa-pencil"></i>
                    <% end %>&nbsp;&nbsp;
                  <%= link_to edit_education_path(education),title:"edit establishment"  do %>
                        <i class="fa fa-edit"></i>
                    <% end %>&nbsp;&nbsp;
                  <%= link_to education_path(education),title:"delete establishment", method: :delete, data: {confirm: "Are you sure you want to delete establishment"} do %>
                        <i class="fa fa-trash-o"></i>
                    <% end %>&nbsp;&nbsp;
                <% end %>
              </span>
                </div>
              </div>
          <% end %>
        </div>
      </section>
    </div>
  </div>
</div><!--//container-->
<br><br>
<br><br>

app/views/educations/new.html.erb
<% provide(:title, 'New School')%>
<!--Breadcrumb-->
<header class="header-top">
  <ul class="breadcrumb">
    <div class="row">
      <div class="col-md-9">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <%= link_to root_path, class:"btn btn-info", method: :get do %><i class="fa fa-home"></i><% end %>
          <%= link_to educations_path,class:"btn btn-info" do %><i class="fa">education</i><% end %>
          <%= link_to new_education_path,class:"btn btn-info" do %><i class="fa">new</i><% end %>

        </div>
      </div>
    </div>
  </ul>
</header>

<div class="container-fluid">
  <div class="education section">
    <div class="section-inner">
      <h2 class="heading">New School</h2>
          <%= render 'educations/form' %>
    </div>
  </div>
</div>

app/views/educations/show.html.erb
<% provide(:title, "#{@education.university}")%>
<!--Breadcrumb-->
<header class="header-top">
  <ul class="breadcrumb">
    <div class="row">
      <div class="col-md-9">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <%= link_to root_path,class:"btn btn-info", method: :get do %><i class="fa fa-home"></i><% end %>
          <%= link_to educations_path,class:"btn btn-info" do %><i class="fa"> schools</i><% end %>
          <!--<%#= link_to institution_certificates_path(@institution),class:"btn btn-info" do %><i class="fa"> certificates</i><%# end %>-->
          <%= link_to education_path(@education),class:"btn btn-info" do %><i class="fa"> <%= @education.university %></i><% end %>
          <!--<%#= link_to education_courses_path(@education),class:"btn btn-info" do %><i class="fa"> courses</i><%# end %>-->
        </div>
      </div>
      <div class="col-md-3">
        <% if user_signed_in? %>
            &nbsp;<span class="control">
                <%= link_to new_education_course_path(@education, @course), class:"active btn btn-info btn-lg pull-right" do %>
                    <i class="fa fa-edit"> Add New Course</i>
                <% end %>
          </span>
        <% end %>
      </div>
    </div>
  </ul>
</header>

<!--Courses List-->

<div class="container-fluid">
  <div class="section">
    <div class="section-inner">
      <h2 class="heading"> Achievements</h2>
      <div class="table-responsive">
        <table class="table table-hover table-expandable table-striped ">
          <thead>
          <tr>
            <th><i class="fa fa-expand"></i></th>
            <th>Title</th>
            <th>Grade</th>

          </tr>
          </thead>
          <tbody>
          <% @courses.each do |course| %>
              <tr>
                <td><%= image_tag course.establishment_logo.url(:thumb), class:'profile_image small-avatar image-responsive'%>
                </td>
                <td><%= course.course_title %></td>
                <td><%= course.course_grade %></td>


              </tr>
              <tr>
                <td colspan="5"><h4>Title: <%= course.course_title %></h4>
                  <h6>Grade: <%= course.course_grade %></h6>
                  <h5>Establishment:  <%= course.establishment %> </h5>
                  <h5>Instructor:  <%= course.instructor %> </h5>
                  <p class="course_description"><%= course.description %></p>
                   <span class="pull-right">
             &nbsp;&nbsp;

                     <% if user_signed_in? %>

                         <%= link_to edit_education_course_path(course.education_id, course.id),title:"edit course"  do %>
                        <i class="fa fa-edit"></i>
                    <% end %>&nbsp;&nbsp;
                         <%= link_to education_course_path(course.education_id, course.id) ,title:"delete course", method: :delete, data: {confirm: "Are you sure you want to delete establishment"} do %>
                        <i class="fa fa-trash-o"></i>
                    <% end %>&nbsp;&nbsp;
                <% end %>
              </span>


                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div><!--//section-inner-->
  </div><!--//section-->
</div><!--//container-fluid-->





<script>
    (function ($) {
        $(function () {
            $('.table-expandable').each(function () {
                var table = $(this);
                table.children('thead').children('tr').append('<th></th>');
                table.children('tbody').children('tr').filter(':odd').hide();
                table.children('tbody').children('tr').filter(':even').click(function () {
                    var element = $(this);
                    element.next('tr').toggle('slow');
                    element.find(".table-expandable-arrow").toggleClass("up");
                });
                table.children('tbody').children('tr').filter(':even').each(function () {
                    var element = $(this);
                    element.append('<td><div class="table-expandable-arrow"></div></td>');
                });
            });
        });
    })(jQuery);
</script>